language: objective-c

before_install:
  - sudo easy_install cpp-coveralls

cache:
  directories:
    - vendor/bundle

install:
  - bundle install --deployment

before_script:
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" != "false" ] && MTB_PR=1 || echo "This is master or not PR"'
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && MTB_MERGE_MASTER=1 || echo "This is not master or PR"'
  - '[ "$MTB_MERGE_MASTER" ] && [ ! "$TRAVIS_TAG" ] && MTB_MASTER_NOT_TAGGED=1 || echo "This is not MTB_MERGE_MASTER or not tagged"'
  - echo TRAVIS_BRANCH=${TRAVIS_BRANCH}
  - echo TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}
  - echo TRAVIS_TAG=${TRAVIS_TAG}
  - echo MTB_PR=${MTB_PR}
  - echo MTB_MERGE_MASTER=${MTB_MERGE_MASTER}
  - echo MTB_MASTER_NOT_TAGGED=${MTB_MASTER_NOT_TAGGED}

script:
  - make test
  - make ipa

after_success:
  - make send-coverage

before_deploy:
  - make deploygate

deploy:
  provider: releases
  api_key:
    secure: gvj2V09zMPsHDPhNoQCpP4ouMUqq7mdq7g2l79dRSTOqGh/diJpgRWKCOZdZ5hYibpe0ynDckixS3ZLyPGhsvx7qfCxNcWDpdmtZtSSv7yuoc3PEbV56QtFfaoCCJacHWohKjRd2+hymDs6bxfPQ3WjnaMAbA48CdEY3QQEftpg=
  file: DemoApp.ipa
  skip_cleanup: true
  on:
    repo: yoheimuta/mtburn-ios-sdk-demoapp
    tags: true
    all_branches: true  # https://github.com/travis-ci/travis-ci/issues/1675

after_script:
  - make remove-certificates

notifications:
  slack:
    rooms:
      - greatmuta:NoziZIr4ddvZYSQUuDplKQma

env:
  global:
    # to decode p12
    - secure: fArJhMTQ9NcJb6+t2YsloRxFQdtF5rxLI1WVlt4ffvFTNAokg19IVov5HZP1i4/THexEWqzhwaAV8X+XZyHc9pqNUutbmeDMChih4m/hbUAy2N0HfQH0yVg3UZMEHzhOmVUBXf36GCnZkmVu6ggTc2TIs5cemRZrkwvK2/JPY+Y=
    # to access iOS Provisioning Portal
    - secure: R2hDwuXaoNNjlJHxtT8DglIjbXR8TSe6XC2tnzlGy9+hLWTXNxK9G4jp2h8sdwBS5grar8w88zyvLEcAXx8a6i6aaYK5JzAYpF5vh1/56ctwCWPx10wrh3jQkkLvJutDDhTaRzcjELOJjF2qdpuqeKYf8CMjUYgIY5bxbjfZj8c=
    # to deploy to deploygate
    - secure: SdVhwFZ0v1ucWO2/rfnJQIuQK7EM++uXMUs1DLW5WEzd5C9kkNiA84D9L/919omfFSXK3Ea4bAp9O1fRdsy9fXVkQ/ypxLXf5Db57eSmtoIlzo8+RlopRP7etcauXn6Lq9M8yjnA399W65v0jYcfeG4GbPnzQLgBWLy/7+k0OsI=

